name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.124.1"

      - name: Build
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: asurati/wip
          force_orphan: true
# Note that config.yaml sets publishDir to /tmp/wip.
# So that is the path given here.
          publish_dir: /tmp/wip
          user_name: asurati
          user_email: asurati@users.noreply.github.com 
          publish_branch: main
